### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by lapis-zero09** [lapis-zero09/lapis_zero09.xyz#2]
make column "ssl"

**Comment by Shandy-ko** [comment]
Done
https://github.com/Shandy-ko/lapis_zero09.github.io/commit/823396ae923a384b01975f1e87b107eb697bc875

**Comment by lapis-zero09** [comment]
Done
https://github.com/Shandy-ko/lapis_zero09.github.io/commit/823396ae923a384b01975f1e87b107eb697bc875
